### ISSUE TITLE
Missing operand

### ISSUE THREAD

**Issue by i-m-alexander** [sergeiown/batch_PDF_compressor#7]
Windows Server 2016. At startup there is message: missing operand, no such message in log file. After this message delete original file after compress didn't work. There is one original and one file named *_compressed.

**Comment by sergeiown** [comment]
> Windows Server 2016. At startup there is message: missing operand, no such message in log file. After this message delete original file after compress didn't work. There is one original and one file named *_compressed.

Bat files are available, if you want to change them for yourself - you are welcome

As mentioned in the readme:
* - Tested on windows 10 and windows 11 x64 systems. The scripts have not been tested on earlier versions.
