### ISSUE TITLE
GhostScript is not installed

### ISSUE THREAD

**Issue by RandomAnimeGamer** [sergeiown/batch_PDF_compressor#9]
I have installed both 32-bit and 64-bit AGPL, yet this tool claims I haven't installed it at all.

----------------------------------------------------------------

Ghostscript is not installed.

Download and install Ghostscript from any of the following links:

https://ghostscript.com/releases/gsdnld.html

https://github.com/ArtifexSoftware/ghostpdl-downloads/releases

----------------------------------------------------------------

**Comment by sergeiown** [comment]
Hey there.

The new release should solve your problem.

https://github.com/sergeiown/batch_PDF_compressor/releases/tag/1.3
